version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Moscow
    volumes:
      - /srv/dev-disk-by-uuid-1a192a26-3a0a-4bc6-8b4c-c4c01f8a1208/Plex:/mnt/plex
