version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Moscow
    volumes:
      - /srv/dev-disk-by-uuid-1a192a26-3a0a-4bc6-8b4c-c4c01f8a1208/Transmission:/downloads:rw
      - /srv/dev-disk-by-uuid-1a192a26-3a0a-4bc6-8b4c-c4c01f8a1208/Transmission/Watch:/watch:rw
      - /srv/dev-disk-by-uuid-1a192a26-3a0a-4bc6-8b4c-c4c01f8a1208/Transmission/Config:/config:rw
